export default {
  schemaVersion: null,
  dashboardFormatVersion: '4.0',
  name: 'z_test_absolute',
  description: null,
  properties: null,
  templateEntityType: 'APPLICATION_COMPONENT_NODE',
  associatedEntityTemplates: null,
  minutesBeforeAnchorTime: -1,
  startDate: null,
  endDate: null,
  refreshInterval: 120000,
  backgroundColor: 15395562,
  color: 15395562,
  height: 768,
  width: 1024,
  canvasType: 'CANVAS_TYPE_ABSOLUTE',
  layoutType: '',
  widgetTemplates: null,
  template: false,
  warRoom: false,
}
