export default {
  widgetType: 'MetricLabelWidget',
  title: '',
  height: 50,
  width: 200,
  minHeight: 0,
  minWidth: 0,
  x: 0,
  y: 0,
  label: null,
  description: null,
  drillDownUrl: null,
  useMetricBrowserAsDrillDown: true,
  drillDownActionType: null,
  backgroundColor: 16777215,
  backgroundColors: null,
  backgroundColorsStr: '16777215,16777215',
  color: 4210752,
  fontSize: 12,
  useAutomaticFontSize: true,
  borderEnabled: false,
  borderThickness: 0,
  borderColor: 14408667,
  backgroundAlpha: 1,
  showValues: false,
  formatNumber: true,
  numDecimals: 2,
  removeZeros: true,
  compactMode: false,
  showTimeRange: false,
  renderIn3D: false,
  showLegend: null,
  legendPosition: null,
  legendColumnCount: null,
  startTime: null,
  endTime: null,
  minutesBeforeAnchorTime: 15,
  isGlobal: true,
  propertiesMap: null,
  dataSeriesTemplates: [
    {
      seriesType: 'LINE',
      metricType: 'OTHER',
      showRawMetricName: false,
      colorPalette: null,
      name: 'Series 0',
      metricMatchCriteriaTemplate: {
        entityMatchCriteria: null,
        metricExpressionTemplate: {
          metricExpressionType: 'Absolute',
          functionType: 'VALUE',
          displayName: 'null',
          inputMetricText: false,
          inputMetricPath: null,
          metricPath:
            'Business Transaction Performance|Business Transactions|WAS_APP_1|/ibm/console|Average Response Time (ms)',
          scopeEntity: {
            applicationName: '2075ICE.PREPROD',
            entityType: 'APPLICATION_COMPONENT',
            entityName: 'WAS_APP_1',
            scopingEntityType: null,
            scopingEntityName: null,
            subtype: null,
          },
        },
        rollupMetricData: true,
        expressionString: '',
        useActiveBaseline: false,
        sortResultsAscending: false,
        maxResults: 20,
        evaluationScopeType: null,
        baselineName: null,
        applicationName: '2075ICE.PREPROD',
        metricDisplayNameStyle: 'DISPLAY_STYLE_AUTO',
        metricDisplayNameCustomFormat: null,
      },
      axisPosition: null,
    },
  ],
  text: null,
  textAlign: 'RIGHT',
  margin: 15,
  showLabel: false,
}
