export default {
  widgetType: 'MetricLabelWidget',
  title: null,
  height: 100,
  width: 200,
  minHeight: 0,
  minWidth: 0,
  x: 231,
  y: 11,
  label: null,
  description: null,
  drillDownUrl: null,
  useMetricBrowserAsDrillDown: true,
  drillDownActionType: null,
  backgroundColor: 16777215,
  backgroundColors: null,
  backgroundColorsStr: '16777215,16777215',
  color: 4210752,
  fontSize: 12,
  useAutomaticFontSize: true,
  borderEnabled: false,
  borderThickness: 0,
  borderColor: 14408667,
  backgroundAlpha: 1,
  showValues: false,
  formatNumber: true,
  numDecimals: 2,
  removeZeros: true,
  compactMode: false,
  showTimeRange: false,
  renderIn3D: false,
  showLegend: null,
  legendPosition: null,
  legendColumnCount: null,
  startTime: null,
  endTime: null,
  minutesBeforeAnchorTime: 15,
  isGlobal: true,
  propertiesMap: null,
  dataSeriesTemplates: [
    {
      seriesType: 'LINE',
      metricType: 'BUSINESS_TRANSACTION',
      showRawMetricName: false,
      colorPalette: null,
      name: 'Series 0',
      metricMatchCriteriaTemplate: {
        entityMatchCriteria: {
          matchCriteriaType: 'SpecificEntities',
          entityType: 'BUSINESS_TRANSACTION',
          agentTypes: null,
          entityNames: [
            {
              applicationName: '1129PCIS_DEV',
              entityType: 'BUSINESS_TRANSACTION',
              entityName: 'PCIS Profile Manager - P1',
              scopingEntityType: 'APPLICATION_COMPONENT',
              scopingEntityName: 'tomcat-p1-PCIS',
              subtype: 'SERVLET',
            },
          ],
          summary: false,
        },
        metricExpressionTemplate: {
          metricExpressionType: 'Logical',
          functionType: 'VALUE',
          displayName: 'null',
          inputMetricText: false,
          inputMetricPath: null,
          relativeMetricPath: 'Average Response Time (ms)',
        },
        rollupMetricData: true,
        expressionString: '',
        useActiveBaseline: false,
        sortResultsAscending: false,
        maxResults: 20,
        evaluationScopeType: 'TIER_AVERAGE',
        baselineName: null,
        applicationName: '1129PCIS_DEV',
        metricDisplayNameStyle: 'DISPLAY_STYLE_AUTO',
        metricDisplayNameCustomFormat: null,
      },
      axisPosition: null,
    },
  ],
  text: null,
  textAlign: 'RIGHT',
  margin: 15,
  showLabel: false,
}
